DROP TABLE IF EXISTS TRANSACTIONS;

CREATE TABLE TRANSACTIONS (
	id BIGINT AUTO_INCREMENT PRIMARY KEY, 
	reference VARCHAR(6) NOT NULL,
	account_iban VARCHAR(24) NOT NULL,
	date_transaction TIMESTAMP,
	amount DOUBLE NOT NULL,
	fee DOUBLE,
	description VARCHAR(100)
);